MODEL:
  NAME: "SEDensenet121"
  NUM_CLASS: 14
  PRETRAINED: True

  INITER:
    NAME: "kaiming_normal_"
    A: 0
    MODE: 'fan_in'
    NONLINEARITY: 'leaky_relu'

DATASET:
  - NAME: "ChestXray-NIHCC"
    IMAGE_DIR: "dataset/ChestXray-NIHCC/images/"
    CSV_PATH: "dataset/ChestXray-NIHCC/Data_Entry_2017.csv"
    LIST_PATH_TRAIN: "dataset/ChestXray-NIHCC/train_val_list.txt"
    LIST_PATH_VAL : "dataset/ChestXray-NIHCC/test_list.txt"
    DOWNSCALE_SHAPE: [224, 224]

    PIL_TRANSFORMS:
      - TYPE: "ColorJitter"
        BRIGHTNESS: 0.01
        CONTRAST: 0.01
        SATURATION: 0.01
      
      - TYPE: "RandomHorizontalFlip"
        P: 0.3
        
      - TYPE: "RandomAffine"
        DEGREES: 3
        TRANSLATE: [0.05, 0.05]
        
    NORM:
      MEAN: [0.485, 0.456, 0.406]
      STD: [0.229, 0.224, 0.225]
      
DATALOADER:
    BATCH_PER_CARD_TRAIN: 16

    BATCH_PER_CARD_VAL: 16

LOSS:
  NAME: "BCEWithLogitsLoss"
  BCE_WEIGHT: [0.0957, 0.0197, 0.1001, 0.1593, 0.0466, 0.0544, 0.0101,
               0.0305, 0.0330, 0.0159, 0.0164, 0.0145, 0.0259, 0.0016]

OPTIMIZER:
  NAME: "Adam"
  LR: 0.001

SCHEDULER:
  NAME: "ReduceLROnPlateau"
  MODE: "min"
  FACTOR: 0.1
  PATIENCE: 5
  VERBOSE: True
  THRESHOLD: 0.0001
  THRESHOLD_MODE: "rel"
  COOLDOWN: 0
  MIN_LR: 0
  EPS: 1.e-08

CUDA_VISIBLE_DEVICES: "4,5,6,7"

LOG_DIR: "train_log/SEDensenet121/"

NUM_EPOCH: 500
